version: '3'
services:
  inventory:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./src:/src/src
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - -p 5000
    environment:
      FLASK_DEBUG: 1
